<%@ Page Title="" Language="C#" MasterPageFile="~/View/Envios/Envios.master" AutoEventWireup="true" CodeBehind="AdministrarEnvios.aspx.cs" Inherits="proyecto.Envios.AdministrarEnvios" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContenidoPrincipal" runat="server">
    <asp:LinkButton ID="Atras" runat="server" OnClick="Atras_Click">Volver atras</asp:LinkButton>
    <h2>Segimientos</h2>
    <div class="static-info" style="box-sizing: border-box; max-width: none !important; margin: 0px !important; padding: 0px !important; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h5 style="box-sizing: border-box; font-weight: 500; line-height: 1.1428em; font-size: 20px; margin-top: 0px; margin-bottom: 12px; font-family: inherit; color: rgb(245, 72, 30);">Despacho a todo Chile</h5>
        <p style="box-sizing: border-box; margin: 0px; color: rgb(130, 130, 130); font-size: 15px;">
            Enviamos tus repuestos a todo Chile mediante Chilexpress y Starken</p>
    </div>
    <img alt="" src="https://http2.mlstatic.com/storage/developers-site-cms-admin/CDV_ME/280812999212-210713-mla-mlu-mlm-mco-mlc-mlb-como-funciona-mercado-envios-icono-01.png" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; max-width: 100%; height: 139px; vertical-align: middle; width: 156px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" /><br class="Apple-interchange-newline" />
    <h5 style="box-sizing: border-box; line-height: 1.1428em; font-size: 20px; margin-top: 0px; margin-bottom: 12px; font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; color: rgb(245, 72, 30); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Consulta donde va tu repuesto mediante ChileXpress</h5>
    <img alt="" src="../../images/qrcode_www.chilexpress.cl.png" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; max-width: 100%; height: 190px; vertical-align: middle; width: 216px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" /><p style="box-sizing: border-box; line-height: 1.1428em; font-size: 20px; margin-top: 0px; margin-bottom: 12px; font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; color: rgb(245, 72, 30); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Consulta donde va tu repuesto mediante Starken</p>
    <p style="box-sizing: border-box; line-height: 1.1428em; font-size: 20px; margin-top: 0px; margin-bottom: 12px; font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; color: rgb(245, 72, 30); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <img alt="" src="../../images/qrcode_www.starken.cl.png" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; max-width: 100%; height: 208px; vertical-align: middle; width: 218px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;segoe ui&quot;, Roboto, &quot;helvetica neue&quot;, Arial, sans-serif, &quot;apple color emoji&quot;, &quot;segoe ui emoji&quot;, &quot;segoe ui symbol&quot;; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" /></p>
    <p>&nbsp;</p>
</asp:Content>
